---
# - name: Add Pulp host to /etc/hosts
#   lineinfile:
#     path: /etc/hosts
#     line: "163.7.144.249 prod-pulp.hpc.nesi.org.nz prod-pulp"
#     state: present
#     create: yes

- name: Ensure SLURM repos
  ansible.builtin.yum_repository: "{{ item }}"
  loop: "{{ nesi_slurm_repo }}"
  loop_control:
    label: "{{ item.name }}"

- name: Update package cache
  ansible.builtin.shell:
    sudo dnf makecache

- name: Install SLURM packages with dependencies
  dnf:
    name: "{{ slurm_packages }}"
    state: present

- name: Setup SLURM group
  ansible.builtin.group:
    name: "slurm"
    system: true
    state: present

- name: Setup SLURM user account
  ansible.builtin.user:
    name: "slurm"
    group: "slurm"
    system: true
    shell: /sbin/nologin
    create_home: false