- name: Install Packages for Apptainer
  dnf:
    name: "{{ dnf_packages }}"
    state: present
    update_cache: true

- name: Ensure Apptainer mnt Session dir exists
  file:
    path: "/var/apptainer/mnt/session/"
    state: directory
    mode: '0755'

- name: Install 99-apptainer.conf to /etc/sysctl.d
  template:
    src: 99-apptainer.conf.j2
    dest: /etc/sysctl.d/99-apptainer.conf
    
- name: Reload sysctl settings from all conf files
  ansible.builtin.command: sudo sysctl --system