galaxy_info:
  author: Kahu Anderson
  description: Ansible role to install Lmod from Source

  license:
    - MIT

  min_ansible_version: 2.0

  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - all
    - name: Rocky
      versions:
        - all

  galaxy_tags:
    - development

dependencies: []