---    
- name: Install additional Packages
  dnf:
    name: "{{ additonal_packages }}"
    state: present

- name: python install ts
  shell: >-
    pip3 install {{ item }}
  with_items: "{{ python_packages }}"

#- name: Install xfce group
#  shell: >-
#    dnf groupinstall -y xfce

- name: Install xfce group
  dnf:
    name: '@xfce'
    state: present

- name: Remove xfce4-screensaver
  dnf:
    name: xfce4-screensaver
    state: absent
    autoremove: false
