dnf_packages:
  # Apptainer requirements
  - e2fsprogs
  - fakeroot
  - fuse-overlayfs
  #- fuse2fs
  - libseccomp
  - squashfs-tools
  - squashfuse
  - cryptsetup
  - apptainer

max_user_namespaces: 16384