---
- name: NeSI Docker base image playbook
  hosts: all
  become: true
  roles:
    - { role: nesi.compute }
    - { role: nesi.slurm }
    - { role: nesi.apptainer }
    - { role: nesi.ood-image }
    - { role: kubectl }
